In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [24]:
A = np.arange(0,10)

In [31]:
a=5
A[0:a], A[a:]

(array([ 0,  1, 11,  3,  4]), array([5, 6, 7, 8, 9]))

In [18]:
C=A.copy()
C[0,0] = 1
A,C

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 0.],
        [0., 0.]]))

In [46]:
A = arange(9).reshape((3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
x = ones((1,3))

In [50]:
A*x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [51]:
A.dot(x)

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [71]:
x = arange(3)

In [72]:
y = arange(3,6)

In [73]:
x, y

(array([0, 1, 2]), array([3, 4, 5]))

In [81]:
einsum('i,i', x, y) , einsum('i,j -> ij', x, y)

(14,
 array([[ 0,  0,  0],
        [ 3,  4,  5],
        [ 6,  8, 10]]))

In [60]:
x = x.reshape((1,3))

In [61]:
x

array([[0, 1, 2]])

In [62]:
x*y

array([[ 0,  4, 10]])

In [63]:
y*x

array([[ 0,  4, 10]])

In [64]:
y = y.reshape((3,1))

In [65]:
A = y*x

array([[ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10]])

In [66]:
y

array([[3],
       [4],
       [5]])

In [67]:
x

array([[0, 1, 2]])

In [69]:
outer(x)

TypeError: _outer_dispatcher() missing 1 required positional argument: 'b'

In [84]:
C = np.ones((3,3,3,3))
T = np.ones((3,3))
K = np.ones((3,3))

einsum('ijkl, kl', C, T) # =sum_k sum_l C[i,j,k,l] T[k,l]

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [107]:
A = arange(0,100)
AC = A.reshape((10,10), order='C')
AF = A.reshape((10,10), order='F')

# for i in range(10):
#     for j in range(10):
#         AC[i,j] == AF[j,i] = A[i*10+j]

In [108]:
AC

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:
x = linspace(-1,1,50)
y = linspace(-1,1,50)

X, Y = meshgrid(x,y)

In [110]:
x.shape, y.shape, X.shape, Y.shape

((50,), (50,), (50, 50), (50, 50))

In [129]:
def norm(a, p = 2):
    if p == 'oo':
        return np.max(abs(a))
    else :
        return (sum(abs(a)**p))**(1/p)

In [130]:
a = array([3,4,5])

In [131]:
a = arange(10).reshape((2,5))

In [132]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [134]:
norm(a, 2)

16.881943016134134

In [135]:
np.linalg.norm?